#!/bin/bash

echo -e "# Regular Colors"

echo -e "| Value    | Color  |\e[0m"
echo -e "| -------- | ------ |\e[0m"
echo -e "| \e[0;30m | Black  |\e[0m"
echo -e "| \e[0;31m | Red    |\e[0m"
echo -e "| \e[0;32m | Green  |\e[0m"
echo -e "| \e[0;33m | Yellow |\e[0m"
echo -e "| \e[0;34m | Blue   |\e[0m"
echo -e "| \e[0;35m | Purple |\e[0m"
echo -e "| \e[0;36m | Cyan   |\e[0m"
echo -e "| \e[0;37m | White  |\e[0m"
                               
echo -e "# Bold               "
                               
echo -e "| Value    | Color  |\e[0m"
echo -e "| -------- | ------ |\e[0m"
echo -e "| \e[1;30m | Black  |\e[0m"
echo -e "| \e[1;31m | Red    |\e[0m"
echo -e "| \e[1;32m | Green  |\e[0m"
echo -e "| \e[1;33m | Yellow |\e[0m"
echo -e "| \e[1;34m | Blue   |\e[0m"
echo -e "| \e[1;35m | Purple |\e[0m"
echo -e "| \e[1;36m | Cyan   |\e[0m"
echo -e "| \e[1;37m | White  |\e[0m"
                               
echo -e "# Underline          "
                               
echo -e "| Value    | Color  |\e[0m"
echo -e "| -------- | ------ |\e[0m"
echo -e "| \e[4;30m | Black  |\e[0m"
echo -e "| \e[4;31m | Red    |\e[0m"
echo -e "| \e[4;32m | Green  |\e[0m"
echo -e "| \e[4;33m | Yellow |\e[0m"
echo -e "| \e[4;34m | Blue   |\e[0m"
echo -e "| \e[4;35m | Purple |\e[0m"
echo -e "| \e[4;36m | Cyan   |\e[0m"
echo -e "| \e[4;37m | White  |\e[0m"
                               
echo -e "# Background         "
                               
echo -e "| Value  | Color  |  \e[0m"
echo -e "| ------ | ------ |  \e[0m"
echo -e "| \e[40m | Black  |  \e[0m"
echo -e "| \e[41m | Red    |  \e[0m"
echo -e "| \e[42m | Green  |  \e[0m"
echo -e "| \e[43m | Yellow |  \e[0m"
echo -e "| \e[44m | Blue   |  \e[0m"
echo -e "| \e[45m | Purple |  \e[0m"
echo -e "| \e[46m | Cyan   |  \e[0m"
echo -e "| \e[47m | White  |  \e[0m"
                               
echo -e "# High Intensity     "
                               
echo -e "| Value    | Color  |\e[0m"
echo -e "| -------- | ------ |\e[0m"
echo -e "| \e[0;90m | Black  |\e[0m"
echo -e "| \e[0;91m | Red    |\e[0m"
echo -e "| \e[0;92m | Green  |\e[0m"
echo -e "| \e[0;93m | Yellow |\e[0m"
echo -e "| \e[0;94m | Blue   |\e[0m"
echo -e "| \e[0;95m | Purple |\e[0m"
echo -e "| \e[0;96m | Cyan   |\e[0m"
echo -e "| \e[0;97m | White  |\e[0m"
                               
echo -e "# Bold High Intensity"
                               
echo -e "| Value    | Color  |\e[0m"
echo -e "| -------- | ------ |\e[0m"
echo -e "| \e[1;90m | Black  |\e[0m"
echo -e "| \e[1;91m | Red    |\e[0m"
echo -e "| \e[1;92m | Green  |\e[0m"
echo -e "| \e[1;93m | Yellow |\e[0m"
echo -e "| \e[1;94m | Blue   |\e[0m"
echo -e "| \e[1;95m | Purple |\e[0m"
echo -e "| \e[1;96m | Cyan   |\e[0m"
echo -e "| \e[1;97m | White  |\e[0m"
         
echo -e "# High Intensity backgrounds"
         
echo -e "| Value     | Color  |\e[0m"
echo -e "| --------- | ------ |\e[0m"
echo -e "| \e[0;100m | Black  |\e[0m"
echo -e "| \e[0;101m | Red    |\e[0m"
echo -e "| \e[0;102m | Green  |\e[0m"
echo -e "| \e[0;103m | Yellow |\e[0m"
echo -e "| \e[0;104m | Blue   |\e[0m"
echo -e "| \e[0;105m | Purple |\e[0m"
echo -e "| \e[0;106m | Cyan   |\e[0m"
echo -e "| \e[0;107m | White  |\e[0m"

echo -e "\e[1mbold\e[0m"
echo -e "\e[3mitalic\e[0m"
echo -e "\e[3m\e[1mbold italic\e[0m"
echo -e "\e[4munderline\e[0m"
echo -e "\e[9mstrikethrough\e[0m"

echo -e "# Reset"

echo -e "| Value | Color  | "
echo -e "| ----- | ------ | "
echo -e "| \e[0m | Reset  | "
