######ALIASES######
######SSH######
    alias "v4ult22=ssh operator@192.168.0.245"
    alias "gn051s=ssh deck@192.168.0.26"
    alias "sshfsv=sshfs -o allow_other operator@192.168.0.245:/home/operator/ ~/V4ULTXXII'"
    alias "sshfsg=sshfs deck@192.168.0.12:/home/deck/ ~/DataForts/GN0515"
######SHELL ALIASES######
    alias "mp=mocp"
    alias "ls=exa"
    alias "flr=faillock --reset"
    alias "pp=powerprofilesctl"
######APPS######
    ###BLUETOOTH###
    alias "bts=sudo systemctl disable bluetooth.service && sudo systemctl status bluetooth.service"
    alias "bto=sudo systemctl enable bluetooth.service && sudo systemctl status bluetooth.service"
    alias "tm=tmux"
    ###TMUXALIASES###
        alias "tmks=tmux kill-session"
        alias "tmka=tmux kill-server"
        alias "tmns=tmux new-session"
        alias "tmls=tmux ls"
        alias "tmdt=tmux detach"
        alias "tmat=tmux attach"
    alias "nw=nmcli"
    alias "nv=nvim"
######NAVIGATION#######
    alias ".ca=cd ~/.cache;ls -a"
    alias ".co=cd ~/.config;ls -a"
    alias ".lo=cd ~/.local;ls -a" 
    alias "DF=cd ~/DataForts;ls -a"
    alias "DE=cd ~/Desktop;ls -a"
    alias "DC=cd ~/Documents;ls -a"
    alias "MU=cd ~/Music;ls -a"
    alias "DL=cd ~/Downloads;ls -a"
    alias "PI=cd ~/Pictures;ls -a"
    alias "SC=cd ~/Scripts;ls -a"
    alias "VI=cd ~/Videos;ls -a"
    alias "GT=cd ~/Gits;ls -a"
    alias "h=~/;ls -a"
    alias "rn=/run/media/operator;ls -a"
######PWRMANAGEMENT######
    alias "SD=sudo shutdown now"
    alias "RB=sudo reboot"
    alias "SU=sudo systemctl suspend"
######SCRIPTS######
    alias "TTY=~/Scripts/ttydock.sh"
    alias "tb=cl;~/Scripts/TMBOOT.sh"
    alias "ud=~/Scripts/ud.sh"
    alias "BU=~/Scripts/backups.sh"
    alias "vcm=~/Scripts/vcm.sh"
    alias "vcd=veracrypt --dismount"
    alias "BU=~/Scripts/backups.sh"
    alias "udb=~/Scripts/UNLOCKDB.sh"
    alias "dm=~/Scripts/DMTB.sh"
    alias "tbm=~/Scripts/tbm.sh"
    alias "tarot=/home/operator/Gits/bash-the-tarot/bash_the_tarot.sh"
    alias "rnnrbu=~/Scripts/rnnrzip.sh"
    alias "3ct=~/Scripts/3ctarot.sh"
    alias "acp=~/Scripts/ansigradients.sh"
    alias "theme=~/Documents/friedrice/themeschange.sh" 
    alias "bf=~/Scripts/bashfetch.sh" 
#echo "tmcp=remind me tmux copy actions"
    alias "tmcp=~/Scripts/tmcprm.sh"

